name: snippets
description: A package for parsing and manipulating code samples in Flutter repo dartdoc comments.
repository: https://github.com/flutter/assets-for-api-docs/tree/main/packages/snippets
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+snippets%22
version: 0.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
<<<<<<< Updated upstream
  analyzer: ^6.1.0
  args: ^2.0.0
  dart_style: ^2.3.1
  file: ^6.1.0
  interval_tree: ^0.3.0
  meta: ^1.3.0
  path: ^1.8.0
  platform: ^3.0.0
  process: ^4.2.4
  pub_semver: ^2.0.0
  quiver: ^3.0.0
  recase: ^4.0.0
=======
  # analyzer: ^6.2.0
  # args: ^2.0.0
  # dart_style: ^2.3.1
  # file: ^6.1.4
  # interval_tree: ^0.3.0
  # meta: ^1.3.0
  # path: ^1.8.0
  # platform: ^3.0.0
  # process: ^4.2.4
  # pub_semver: ^2.0.0
  # quiver: ^3.0.0
  # recase: ^4.0.0
  _fe_analyzer_shared: 64.0.0
  analyzer: 6.2.0
  args: 2.4.2
  async: 2.11.0
  boolean_selector: 2.1.1
  collection: 1.18.0
  convert: 3.1.1
  crypto: 3.0.3
  dart_style: 2.3.3
  file: 6.1.4
  glob: 2.1.2
  interval_tree: 0.3.0
  matcher: 0.12.16
  meta: 1.11.0
  package_config: 2.1.0
  path: 1.8.3
  platform: 3.1.3
  process: 4.2.4
  pub_semver: 2.1.4
  quiver: 3.2.1
  recase: 4.1.0
  source_span: 1.10.0
  stack_trace: 1.11.1
  stream_channel: 2.1.2
  string_scanner: 1.2.0
  term_glyph: 1.2.1
  test_api: 0.6.1
  typed_data: 1.3.2
  watcher: 1.1.0
  yaml: 3.1.2
>>>>>>> Stashed changes

dev_dependencies:
  test: ^1.21.1

executables:
  snippets:



